### ISSUE TITLE
Clarity on the Installation

### ISSUE THREAD

**Issue by sclewis90** [brummer10/neural-amp-modeler-ui#4]
I cannot figure out how to install this. I installed NAM lv2 and it works fine, but could you please give more detailed instructions on how to install this?

**Comment by brummer10** [comment]
It just depend on were you've installed the NAM LV2 plug. If you've installed it into $HOME/.lv2 just run 
`make install`
if you've installed it into /usr/lib/lv2 you must use
`sudo make install`

The makefile checks if it find the NAM LV2 plug, if not, it wont install anything, so it wouldn't harm if you try the wrong selection. If both not work, let me know were you've put the NAM LV2 plug and if you've changed the name of the directory that the NAM build script produce.

**Comment by sclewis90** [comment]
> It just depend on were you've installed the NAM LV2 plug. If you've installed it into $HOME/.lv2 just run `make install` if you've installed it into /usr/lib/lv2 you must use `sudo make install`
> 
> The makefile checks if it find the NAM LV2 plug, if not, it wont install anything, so it wouldn't harm if you try the wrong selection. If both not work, let me know were you've put the NAM LV2 plug and if you've changed the name of the directory that the NAM build script produce.

I'm still not quite sure how to go about this. So, lets start from the beginning. I have NAM installed in home directory, and I've just downloaded and extracted the zip of the GUI, what individual steps do I take?

**Comment by brummer10** [comment]
Okay, that wouldn't work.
You must clone the repository, download the zip didn't work (old outstanding github issue)
so the steps to build and install been
```
git clone https://github.com/brummer10/neural-amp-modeler-ui.git
cd ./neural-amp-modeler-ui
git submodule init
git submodule update
make
make install
```

dependencies to build and run it been
```
    libcairo2-dev
    libx11-dev
    lv2-dev
```
depending on your distribution they may have different but similar names. You must install those with your package manager before you are able to build the GUI.

**Comment by sclewis90** [comment]
> Okay, that wouldn't work. You must clone the repository, download the zip didn't work (old outstanding github issue) so the steps to build and install been
> 
> ```
> git clone https://github.com/brummer10/neural-amp-modeler-ui.git
> cd ./neural-amp-modeler-ui
> git submodule init
> git submodule update
> make
> make install
> ```
> 
> dependencies to build and run it been
> 
> ```
>     libcairo2-dev
>     libx11-dev
>     lv2-dev
> ```
> 
> depending on your distribution they may have different but similar names. You must install those with your package manager before you are able to build the GUI.

awesome, thank you very much for this project and the clarity on installation

**Comment by sclewis90** [comment]
it works!

**Comment by brummer10** [comment]
You are welcome.
