### ISSUE TITLE
Crash when browsing large folder in ListView mode

### ISSUE THREAD

**Issue by sirsipe** [brummer10/neural-amp-modeler-ui#7]
"Stack smashing detected" when  scrolling over about 200 .nam files.

Video demostration: https://www.youtube.com/watch?v=Jsfu-YpCu00

**Comment by brummer10** [comment]
Thanks for reporting and the video demonstration. 
Latest revision should fix the issue.

**Comment by sirsipe** [comment]
Fix confirmed! Thank you for very fast response!
